# Shell variables
# Generated by 'wal'
wallpaper='/home/jajo/Wallpapers/minimal.jpg'

# Special
background='#102130'
foreground='#e0edf5'
cursor='#e0edf5'

# Colors
color0='#102130'
color1='#85bfd6'
color2='#84bad6'
color3='#9eccde'
color4='#b2d6e5'
color5='#c2deea'
color6='#cfdcef'
color7='#e0edf5'
color8='#9ca5ab'
color9='#85bfd6'
color10='#84bad6'
color11='#9eccde'
color12='#b2d6e5'
color13='#c2deea'
color14='#cfdcef'
color15='#e0edf5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
