--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jajo/Wallpapers/minimal.jpg"

-- Special
background="#102130"
foreground="#e0edf5"
cursor="#e0edf5"

-- Colors
color0="#102130"
color1="#85bfd6"
color2="#84bad6"
color3="#9eccde"
color4="#b2d6e5"
color5="#c2deea"
color6="#cfdcef"
color7="#e0edf5"
color8="#9ca5ab"
color9="#85bfd6"
color10="#84bad6"
color11="#9eccde"
color12="#b2d6e5"
color13="#c2deea"
color14="#cfdcef"
color15="#e0edf5"
